spring:
  datasource:
    url: jdbc:mysql://localhost:8001/alura
    username: user
    password: root
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${JWT_SECRET:123123}